### ISSUE TITLE
Question regarding node.c

### ISSUE THREAD

**Issue by saukol** [munin-monitoring/munin-c#34] opened 2017-08-29 12:51 UTC
Hi ,

Below is the code from line 470-486 of node.c. If you check the lines 475 and 482 (which are in bold letters) , in 475 it is checking (ret_val =! 0) and in 482 it is checking (ret_val != 0). IS that exactly like that only  or is it an error? 

/* setuid/gid */
	if (geteuid() == 0) {
		/* We *are* root */
		int ret_val;
		ret_val = setgid(pconf.gid);
		**if ((ret_val =! 0) || (getgid() != pconf.gid)) {**
				perror("gid not changed by setgid");
				abort();
		}

		/* Change UID *after* GID, otherwise cannot change anymore */
		ret_val = setuid(pconf.uid);
		**if ((ret_val != 0) || (getuid() != pconf.uid)) {**
			perror("uid not changed by setuid");
			abort();
		}
}

**Comment by stevejames** [comment] 2017-09-02 16:55
Yep, that's an error. "ret_val =! 0" is an assignment of '!0' to 'ret_val' not a comparison against '0' as intended. And since '!0' is true, the program will always abort here.

This bug is easy to do and difficult to spot. I write this kind of comparison the other way around: "0 != ret_val" because "0 =! ret_val" is a syntax error.

**Comment by steveschnepp** [comment] 2017-09-04 07:38
Well, it's fixed in 3317489a7d4f12d3978752b2979f62e727a24453 which is in the coverity branch. I have to merge it in master.

**Closed** 2017-09-04 10:54 UTC
